CREATE DATABASE TouristGuide;

CREATE TABLE attraction (
ID int NOT NULL auto_increment PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(500) NOT NULL,
IMAGE_PATH VARCHAR(500) NOT NULL
);

CREATE TABLE season (
SEASON_ID int NOT NULL auto_increment PRIMARY KEY,
SEASON_NAME VARCHAR(50)
);

CREATE TABLE tags (
TAGS_ID int NOT NULL auto_increment PRIMARY KEY,
TAGS_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE tagsidentifier (
TAGS_ID int NOT NULL,
ATTRACTION_ID int NOT NULL,
PRIMARY KEY (TAGS_ID, ATTRACTION_ID)
);

CREATE TABLE city (
CITY_ID int NOT NULL auto_increment PRIMARY KEY,
CITY_NAME VARCHAR(50) NOT NULL
);
