/*CREATE DATABASE TouristGuide;

CREATE TABLE touristguide.attraction (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    IMAGE_PATH VARCHAR(500) NOT NULL,
    City_ID INT NOT NULL,
);


CREATE TABLE tags (
TAGS_ID int NOT NULL auto_increment PRIMARY KEY,
TAGS_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE touristguide.attraction_tags (
    ATTRACTION_ID INT NOT NULL,
    TAGS_ID INT NOT NULL,
    PRIMARY KEY (ATTRACTION_ID, TAGS_ID),
    FOREIGN KEY (ATTRACTION_ID) REFERENCES touristguide.attraction(ID),
    FOREIGN KEY (TAGS_ID) REFERENCES touristguide.tags(TAGS_ID)
);

CREATE TABLE city (
CITY_ID int NOT NULL auto_increment PRIMARY KEY,
CITY_NAME VARCHAR(50) NOT NULL
);
*/